/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-09 05:45:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.travelplanner.model.User;
import java.util.List;
import com.travelplanner.dao.DestinationDAO;
import com.travelplanner.model.Destination;
import com.travelplanner.dao.BookingDAO;
import com.travelplanner.model.Booking;
import com.travelplanner.service.DBConnection;

public final class admin_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("com.travelplanner.model.Destination");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.travelplanner.service.DBConnection");
    _jspx_imports_classes.add("com.travelplanner.dao.BookingDAO");
    _jspx_imports_classes.add("com.travelplanner.dao.DestinationDAO");
    _jspx_imports_classes.add("com.travelplanner.model.User");
    _jspx_imports_classes.add("com.travelplanner.model.Booking");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User user = (User) session.getAttribute("user");
    if (user == null || !"admin".equals(user.getRole())) {
        response.sendRedirect("login.jsp");
        return;
    }
    List<Destination> destinations = null;
    List<Booking> bookings = null;
    try {
        DestinationDAO destDao = new DestinationDAO(DBConnection.getConnection());
        destinations = destDao.getAllDestinations();
        BookingDAO bookingDao = new BookingDAO(DBConnection.getConnection());
        bookings = bookingDao.getBookingsByUser(-1); // -1 means get all bookings (see note below)
    } catch (Exception e) {
        destinations = null;
        bookings = null;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>Admin Panel - Travel Planner</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background: #f7fafd;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("        .navbar {\n");
      out.write("            width: 100%;\n");
      out.write("            background: linear-gradient(90deg, #2980b9 0%, #6dd5fa 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            padding: 0.7em 0;\n");
      out.write("            box-shadow: 0 2px 8px rgba(41,128,185,0.08);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 100;\n");
      out.write("        }\n");
      out.write("        .navbar .logo {\n");
      out.write("            font-size: 1.7em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-left: 2em;\n");
      out.write("            letter-spacing: 2px;\n");
      out.write("        }\n");
      out.write("        .navbar ul {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("        .navbar ul li {\n");
      out.write("            margin: 0 1.2em;\n");
      out.write("        }\n");
      out.write("        .navbar ul li a {\n");
      out.write("            color: #fff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: color 0.2s;\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("        }\n");
      out.write("        .navbar ul li a:hover, .navbar ul li a.active {\n");
      out.write("            background: rgba(255,255,255,0.18);\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("        .navbar .user-info {\n");
      out.write("            margin-right: 2em;\n");
      out.write("            font-size: 1em;\n");
      out.write("            font-weight: 500;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        .navbar .user-info span {\n");
      out.write("            margin-right: 1em;\n");
      out.write("        }\n");
      out.write("        .admin-panel-section {\n");
      out.write("            max-width: 1100px;\n");
      out.write("            margin: 2.5em auto 0 auto;\n");
      out.write("            padding: 2em 1em;\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 18px;\n");
      out.write("            box-shadow: 0 8px 32px rgba(41,128,185,0.10);\n");
      out.write("        }\n");
      out.write("        .admin-title {\n");
      out.write("            color: #2980b9;\n");
      out.write("            font-size: 2em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1.2em;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .tabs {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-bottom: 2em;\n");
      out.write("        }\n");
      out.write("        .tab-btn {\n");
      out.write("            background: #eaf6fb;\n");
      out.write("            color: #2980b9;\n");
      out.write("            border: none;\n");
      out.write("            padding: 12px 32px;\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border-radius: 8px 8px 0 0;\n");
      out.write("            margin: 0 0.5em;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background 0.2s, color 0.2s;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("        .tab-btn.active, .tab-btn:hover {\n");
      out.write("            background: #2980b9;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("        .tab-content {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        .tab-content.active {\n");
      out.write("            display: block;\n");
      out.write("            animation: fadeIn 0.5s;\n");
      out.write("        }\n");
      out.write("        @keyframes fadeIn {\n");
      out.write("            from { opacity: 0; transform: translateY(20px);}\n");
      out.write("            to { opacity: 1; transform: translateY(0);}\n");
      out.write("        }\n");
      out.write("        .destinations-grid {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 2em;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        .destination-card {\n");
      out.write("            background: linear-gradient(120deg, #6dd5fa 0%, #2980b9 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            box-shadow: 0 4px 16px rgba(41,128,185,0.10);\n");
      out.write("            width: 260px;\n");
      out.write("            max-width: 90vw;\n");
      out.write("            margin-bottom: 1.5em;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 1.5em 1em 1.2em 1em;\n");
      out.write("        }\n");
      out.write("        .destination-card img {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 220px;\n");
      out.write("            height: 130px;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            margin-bottom: 1em;\n");
      out.write("            box-shadow: 0 2px 8px rgba(41,128,185,0.10);\n");
      out.write("        }\n");
      out.write("        .destination-card h3 {\n");
      out.write("            margin: 0.2em 0 0.5em 0;\n");
      out.write("            font-size: 1.3em;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .destination-card p {\n");
      out.write("            font-size: 1em;\n");
      out.write("            margin-bottom: 1.2em;\n");
      out.write("            color: #f0f6fa;\n");
      out.write("        }\n");
      out.write("        .bookings-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 2px 8px rgba(41,128,185,0.08);\n");
      out.write("        }\n");
      out.write("        .bookings-table th, .bookings-table td {\n");
      out.write("            padding: 14px 10px;\n");
      out.write("            text-align: left;\n");
      out.write("        }\n");
      out.write("        .bookings-table th {\n");
      out.write("            background: #2980b9;\n");
      out.write("            color: #fff;\n");
      out.write("            font-weight: 600;\n");
      out.write("            border: none;\n");
      out.write("        }\n");
      out.write("        .bookings-table tr {\n");
      out.write("            border-bottom: 1px solid #eaeaea;\n");
      out.write("        }\n");
      out.write("        .bookings-table tr:last-child {\n");
      out.write("            border-bottom: none;\n");
      out.write("        }\n");
      out.write("        .bookings-table td {\n");
      out.write("            color: #333;\n");
      out.write("            background: #f9fbfd;\n");
      out.write("        }\n");
      out.write("        .status-confirmed {\n");
      out.write("            color: #27ae60;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .status-cancelled {\n");
      out.write("            color: #e74c3c;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .status-pending {\n");
      out.write("            color: #f39c12;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .type-icon {\n");
      out.write("            font-size: 1.3em;\n");
      out.write("            margin-right: 0.5em;\n");
      out.write("        }\n");
      out.write("        .no-data {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #888;\n");
      out.write("            font-size: 1.2em;\n");
      out.write("            margin-top: 2em;\n");
      out.write("        }\n");
      out.write("        @media (max-width: 700px) {\n");
      out.write("            .admin-panel-section {\n");
      out.write("                padding: 1em 0.2em;\n");
      out.write("            }\n");
      out.write("            .bookings-table th, .bookings-table td {\n");
      out.write("                padding: 10px 4px;\n");
      out.write("                font-size: 0.95em;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <!-- Font Awesome for icons -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\n");
      out.write("    <script>\n");
      out.write("        function showTab(tab) {\n");
      out.write("            document.getElementById('destinationsTab').classList.remove('active');\n");
      out.write("            document.getElementById('bookingsTab').classList.remove('active');\n");
      out.write("            document.getElementById('destBtn').classList.remove('active');\n");
      out.write("            document.getElementById('bookBtn').classList.remove('active');\n");
      out.write("            document.getElementById(tab + 'Tab').classList.add('active');\n");
      out.write("            document.getElementById(tab + 'Btn').classList.add('active');\n");
      out.write("        }\n");
      out.write("        window.onload = function() {\n");
      out.write("            showTab('destinations');\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"navbar\">\n");
      out.write("        <div class=\"logo\">Travel Planner</div>\n");
      out.write("        <ul>\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard\"><i class=\"fa fa-home\"></i> Dashboard</a></li>\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\"><i class=\"fa fa-search\"></i> Search</a></li>\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookings\"><i class=\"fa fa-suitcase\"></i> My Bookings</a></li>\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin_dashboard\" class=\"active\"><i class=\"fa fa-cogs\"></i> Admin Panel</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <span><i class=\"fa fa-user-circle\"></i> ");
      out.print( user.getName() );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"admin-panel-section\">\n");
      out.write("        <div class=\"admin-title\">\n");
      out.write("            <i class=\"fa fa-cogs\"></i> Admin Panel\n");
      out.write("        </div>\n");
      out.write("        <div class=\"tabs\">\n");
      out.write("            <button class=\"tab-btn\" id=\"destBtn\" onclick=\"showTab('destinations')\"><i class=\"fa fa-map-marked-alt\"></i> Destinations</button>\n");
      out.write("            <button class=\"tab-btn\" id=\"bookBtn\" onclick=\"showTab('bookings')\"><i class=\"fa fa-suitcase-rolling\"></i> Bookings</button>\n");
      out.write("        </div>\n");
      out.write("        <!-- Destinations Tab -->\n");
      out.write("        <div class=\"tab-content\" id=\"destinationsTab\">\n");
      out.write("            <div class=\"destinations-grid\">\n");
      out.write("                ");

                    if (destinations != null && !destinations.isEmpty()) {
                        for (Destination dest : destinations) {
                
      out.write("\n");
      out.write("                    <div class=\"destination-card\">\n");
      out.write("                        <img src=\"");
      out.print( dest.getImageUrl() );
      out.write("\" alt=\"");
      out.print( dest.getName() );
      out.write("\">\n");
      out.write("                        <h3>");
      out.print( dest.getName() );
      out.write("</h3>\n");
      out.write("                        <p>");
      out.print( dest.getDescription() );
      out.write("</p>\n");
      out.write("                    </div>\n");
      out.write("                ");

                        }
                    } else {
                
      out.write("\n");
      out.write("                    <div class=\"no-data\">\n");
      out.write("                        <i class=\"fa fa-map-marked-alt\"></i> No destinations found.\n");
      out.write("                    </div>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Bookings Tab -->\n");
      out.write("        <div class=\"tab-content\" id=\"bookingsTab\">\n");
      out.write("            ");

                if (bookings != null && !bookings.isEmpty()) {
            
      out.write("\n");
      out.write("            <table class=\"bookings-table\">\n");
      out.write("                <tr>\n");
      out.write("                    <th>Booking ID</th>\n");
      out.write("                    <th>User ID</th>\n");
      out.write("                    <th>Type</th>\n");
      out.write("                    <th>Status</th>\n");
      out.write("                    <th>Payment ID</th>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    for (Booking b : bookings) {
                        String icon = "fa-question-circle";
                        if ("destination".equalsIgnoreCase(b.getType())) icon = "fa-map-marker-alt";
                        else if ("flight".equalsIgnoreCase(b.getType())) icon = "fa-plane";
                        else if ("hotel".equalsIgnoreCase(b.getType())) icon = "fa-hotel";
                        else if ("activity".equalsIgnoreCase(b.getType())) icon = "fa-hiking";
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( b.getId() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( b.getUserId() );
      out.write("</td>\n");
      out.write("                    <td>\n");
      out.write("                        <i class=\"fa ");
      out.print( icon );
      out.write(" type-icon\"></i>\n");
      out.write("                        ");
      out.print( b.getType().substring(0,1).toUpperCase() + b.getType().substring(1) );
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    <td class=\"status-");
      out.print( b.getStatus().toLowerCase() );
      out.write("\">\n");
      out.write("                        ");
      out.print( b.getStatus().substring(0,1).toUpperCase() + b.getStatus().substring(1) );
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    <td>");
      out.print( b.getPaymentId() );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </table>\n");
      out.write("            ");

                } else {
            
      out.write("\n");
      out.write("            <div class=\"no-data\">\n");
      out.write("                <i class=\"fa fa-calendar-times\"></i> No bookings found.\n");
      out.write("            </div>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
