/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-09 05:45:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.travelplanner.model.Hotel;

public final class hotels_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.travelplanner.model.Hotel");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Object userObj = session.getAttribute("user");
    if (userObj == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    List<Hotel> hotels = (List<Hotel>) request.getAttribute("hotels");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>Hotels - Travel Planner</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body { background: #f7fafd; margin: 0; padding: 0; }\n");
      out.write("        .hotels-section {\n");
      out.write("            max-width: 900px;\n");
      out.write("            margin: 2.5em auto 0 auto;\n");
      out.write("            padding: 2em 1em;\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 18px;\n");
      out.write("            box-shadow: 0 8px 32px rgba(41,128,185,0.10);\n");
      out.write("        }\n");
      out.write("        .hotels-title {\n");
      out.write("            color: #2980b9;\n");
      out.write("            font-size: 2em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1.2em;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .hotels-grid {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 2em;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        .hotel-card {\n");
      out.write("            background: linear-gradient(120deg, #6dd5fa 0%, #2980b9 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            box-shadow: 0 4px 16px rgba(41,128,185,0.10);\n");
      out.write("            width: 260px;\n");
      out.write("            max-width: 90vw;\n");
      out.write("            margin-bottom: 1.5em;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 1.5em 1em 1.2em 1em;\n");
      out.write("        }\n");
      out.write("        .hotel-card img {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 220px;\n");
      out.write("            height: 130px;\n");
      out.write("            object-fit: cover;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            margin-bottom: 1em;\n");
      out.write("            box-shadow: 0 2px 8px rgba(41,128,185,0.10);\n");
      out.write("        }\n");
      out.write("        .hotel-card h3 {\n");
      out.write("            margin: 0.2em 0 0.5em 0;\n");
      out.write("            font-size: 1.3em;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .hotel-card p {\n");
      out.write("            font-size: 1em;\n");
      out.write("            margin-bottom: 1.2em;\n");
      out.write("            color: #f0f6fa;\n");
      out.write("        }\n");
      out.write("        .hotel-card .price {\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1em;\n");
      out.write("        }\n");
      out.write("        .book-btn {\n");
      out.write("            background: #fff;\n");
      out.write("            color: #2980b9;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 28px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 1em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background 0.3s, color 0.3s;\n");
      out.write("        }\n");
      out.write("        .book-btn:hover {\n");
      out.write("            background: #2980b9;\n");
      out.write("            color: #fff;\n");
      out.write("            border: 1px solid #fff;\n");
      out.write("        }\n");
      out.write("        .no-hotels {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #888;\n");
      out.write("            font-size: 1.2em;\n");
      out.write("            margin-top: 2em;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"hotels-section\">\n");
      out.write("        <div class=\"hotels-title\">\n");
      out.write("            <i class=\"fa fa-hotel\"></i> Available Hotels\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hotels-grid\">\n");
      out.write("            ");

                if (hotels != null && !hotels.isEmpty()) {
                    for (Hotel hotel : hotels) {
            
      out.write("\n");
      out.write("                <div class=\"hotel-card\">\n");
      out.write("                    <img src=\"");
      out.print( hotel.getImageUrl() );
      out.write("\" alt=\"");
      out.print( hotel.getName() );
      out.write("\">\n");
      out.write("                    <h3>");
      out.print( hotel.getName() );
      out.write("</h3>\n");
      out.write("                    <p>");
      out.print( hotel.getAddress() );
      out.write("</p>\n");
      out.write("                    <div class=\"price\">$");
      out.print( hotel.getPrice() );
      out.write(" per night</div>\n");
      out.write("                    \n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pay\" method=\"get\">\n");
      out.write("                    <input type=\"hidden\" name=\"type\" value=\"hotel\">\n");
      out.write("                    <input type=\"hidden\" name=\"hotelId\" value=\"");
      out.print( hotel.getId() );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"destinationId\" value=\"");
      out.print( hotel.getDestinationId() );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"price\" value=\"");
      out.print( hotel.getPrice() );
      out.write("\">\n");
      out.write("                    <button class=\"book-btn\" type=\"submit\"><i class=\"fa fa-check\"></i> Book Hotel</button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\n");
      out.write("                <div class=\"no-hotels\">\n");
      out.write("                    <i class=\"fa fa-frown\"></i> No hotels found for this destination.\n");
      out.write("                </div>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div style=\"text-align:center; color:#e74c3c; margin-top:1em;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
