/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-09 05:44:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.travelplanner.model.Flight;
import com.travelplanner.model.Trains;
import com.travelplanner.model.Bus;
import com.travelplanner.model.Hotel;

public final class payments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.travelplanner.model.Hotel");
    _jspx_imports_classes.add("com.travelplanner.model.Trains");
    _jspx_imports_classes.add("com.travelplanner.model.Bus");
    _jspx_imports_classes.add("com.travelplanner.model.Flight");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Object userObj = session.getAttribute("user");
    if (userObj == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    String type = (String) request.getAttribute("type");
    int refId = (request.getAttribute("refId") != null) ? (Integer) request.getAttribute("refId") : -1;
    Flight flight = (Flight) request.getAttribute("flight");
    Trains train = (Trains) request.getAttribute("train");
    Bus bus = (Bus) request.getAttribute("bus");
    Hotel hotel = (Hotel) request.getAttribute("hotel");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>Payment - Travel Planner</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body { background: #f7fafd; margin: 0; padding: 0; }\n");
      out.write("        .payment-section {\n");
      out.write("            max-width: 500px;\n");
      out.write("            margin: 3em auto;\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 18px;\n");
      out.write("            box-shadow: 0 8px 32px rgba(41,128,185,0.10);\n");
      out.write("            padding: 2.5em 2em;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .payment-title {\n");
      out.write("            color: #2980b9;\n");
      out.write("            font-size: 2em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1.2em;\n");
      out.write("        }\n");
      out.write("        .summary {\n");
      out.write("            margin-bottom: 2em;\n");
      out.write("        }\n");
      out.write("        .summary img {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 320px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            margin-bottom: 1em;\n");
      out.write("        }\n");
      out.write("        .pay-btn {\n");
      out.write("            background: #2980b9;\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            padding: 14px 40px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 1.1em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background 0.3s;\n");
      out.write("        }\n");
      out.write("        .pay-btn:hover {\n");
      out.write("            background: #6dd5fa;\n");
      out.write("            color: #2980b9;\n");
      out.write("        }\n");
      out.write("        .price {\n");
      out.write("            font-size: 1.2em;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1em;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <!-- Font Awesome for icons -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"payment-section\">\n");
      out.write("        <div class=\"payment-title\">\n");
      out.write("            <i class=\"fa fa-credit-card\"></i> Payment\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary\">\n");
      out.write("            ");
 if ("flight".equals(type) && flight != null) { 
      out.write("\n");
      out.write("                <img src=\"");
      out.print( flight.getImageUrl() );
      out.write("\" alt=\"");
      out.print( flight.getAirline() );
      out.write("\">\n");
      out.write("                <h3>");
      out.print( flight.getAirline() );
      out.write("</h3>\n");
      out.write("                <p>\n");
      out.write("                    <i class=\"fa fa-plane-departure\"></i> <b>From:</b> ");
      out.print( flight.getDeparture() );
      out.write("<br>\n");
      out.write("                    <i class=\"fa fa-plane-arrival\"></i> <b>To:</b> ");
      out.print( flight.getArrival() );
      out.write("\n");
      out.write("                </p>\n");
      out.write("                <div class=\"price\">$");
      out.print( flight.getPrice() );
      out.write("</div>\n");
      out.write("            ");
 } else if ("train".equals(type) && train != null) { 
      out.write("\n");
      out.write("                <img src=\"");
      out.print( train.getImageUrl() );
      out.write("\" alt=\"");
      out.print( train.getOperator() );
      out.write("\">\n");
      out.write("                <h3>");
      out.print( train.getOperator() );
      out.write("</h3>\n");
      out.write("                <p>\n");
      out.write("                    <i class=\"fa fa-train\"></i> <b>From:</b> ");
      out.print( train.getDeparture() );
      out.write("<br>\n");
      out.write("                    <i class=\"fa fa-map-marker-alt\"></i> <b>To:</b> ");
      out.print( train.getArrival() );
      out.write("\n");
      out.write("                </p>\n");
      out.write("                <div class=\"price\">$");
      out.print( train.getPrice() );
      out.write("</div>\n");
      out.write("            ");
 } else if ("bus".equals(type) && bus != null) { 
      out.write("\n");
      out.write("                <img src=\"");
      out.print( bus.getImageUrl() );
      out.write("\" alt=\"");
      out.print( bus.getOperator() );
      out.write("\">\n");
      out.write("                <h3>");
      out.print( bus.getOperator() );
      out.write("</h3>\n");
      out.write("                <p>\n");
      out.write("                    <i class=\"fa fa-bus\"></i> <b>From:</b> ");
      out.print( bus.getDeparture() );
      out.write("<br>\n");
      out.write("                    <i class=\"fa fa-map-marker-alt\"></i> <b>To:</b> ");
      out.print( bus.getArrival() );
      out.write("\n");
      out.write("                </p>\n");
      out.write("                <div class=\"price\">$");
      out.print( bus.getPrice() );
      out.write("</div>\n");
      out.write("            ");
 } else if ("hotel".equals(type) && hotel != null) { 
      out.write("\n");
      out.write("                <img src=\"");
      out.print( hotel.getImageUrl() );
      out.write("\" alt=\"");
      out.print( hotel.getName() );
      out.write("\">\n");
      out.write("                <h3>");
      out.print( hotel.getName() );
      out.write("</h3>\n");
      out.write("                <p>");
      out.print( hotel.getAddress() );
      out.write("</p>\n");
      out.write("                <div class=\"price\">$");
      out.print( hotel.getPrice() );
      out.write(" per night</div>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div style=\"color:#e74c3c;\">Invalid booking type or data not found.</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pay\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"type\" value=\"");
      out.print( type );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"refId\" value=\"");
      out.print( refId );
      out.write("\">\n");
      out.write("            <button class=\"pay-btn\" type=\"submit\"><i class=\"fa fa-check\"></i> Pay and Book</button>\n");
      out.write("        </form>\n");
      out.write("        <div style=\"color:#e74c3c; margin-top:1em;\">");
      out.print( request.getAttribute("error") != null ? request.getAttribute("error") : "" );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
